---
- name: Install Debian packages
  apt: pkg={{item}} state=present update_cache=yes
  with_items:
    - wget
    - curl
    - g++
    - gcc
    - libcurl4-openssl-dev
    - libsasl2-2
    - libsasl2-dev
    - libcurl3
